import os
import requests
import json
import logging
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

def normalize_keys(data: dict) -> dict:
    """
    Defensive engineering: Never trust LLM output schema casing.
    Converts all keys to lowercase and strips whitespace.
    """
    if not isinstance(data, dict):
        return {}
    return {str(k).lower().strip(): v for k, v in data.items()}

def generate_synthetic_telemetry(body: str) -> dict:
    if not GROQ_API_KEY:
         raise ValueError("GROQ_API_KEY is missing.")

    # ONE-SHOT PROMPTING: Force the exact schema and style.
    system_prompt = """You are an elite AI Data Engineer constructing a dataset for a fine-tuning pipeline. 
Your objective is to ingest human-written bug reports and Pull Request resolutions for the LangChain repository, and reverse-engineer them into two distinct outputs:
1. 'raw_log': A highly realistic, messy, unstructured Python/LangChain crash log (Traceback) that represents the EXACT symptom of the bug. 
2. 'rca_schema': A strict JSON object representing the Root Cause Analysis.

You MUST output ONLY a valid JSON object with EXACTLY the keys: 'raw_log' and 'rca_schema'.
The 'rca_schema' MUST contain EXACTLY these keys: severity, failing_service, error_code, root_cause_analysis, recommended_remediation.

=== EXAMPLE INPUT ===
PULL REQUEST AND RELATED ISSUES:
PR: Fix PydanticOutputParser markdown stripping. Resolves #4102.
#4102:
When I chain a prompt with `PydanticOutputParser`, it randomly crashes if the LLM outputs a markdown code block instead of raw JSON.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 256, in __call__
    return self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 26, in parse
    raise OutputParserException(f"Failed to parse Pydantic object: {e}")
langchain.schema.output_parser.OutputParserException: Failed to parse Pydantic object: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

=== EXAMPLE OUTPUT ===
{
  "raw_log": "Traceback (most recent call last):\\n  File \\"/usr/local/lib/python3.10/site-packages/langchain/chains/base.py\\", line 256, in __call__\\n    return self._call(inputs, run_manager=run_manager)\\n  File \\"/usr/local/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py\\", line 26, in parse\\n    raise OutputParserException(f\\"Failed to parse Pydantic object: {e}\\")\\nlangchain.schema.output_parser.OutputParserException: Failed to parse Pydantic object: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)",
  "rca_schema": {
    "severity": "HIGH",
    "failing_service": "langchain.output_parsers.pydantic",
    "error_code": "OutputParserException",
    "root_cause_analysis": "The PydanticOutputParser directly delegates to json.loads() without stripping markdown formatting blocks (e.g., ```json ... ```) that are frequently generated by conversational LLMs. This causes a JSONDecodeError when the parser encounters the markdown backticks.",
    "recommended_remediation": "Update the parser's base logic to include a regex step that strips markdown code block wrappers before attempting to deserialize the JSON string into a Pydantic object."
  }
}
"""

    user_prompt = f"PULL REQUEST AND RELATED ISSUES:\n{body}\n\nGenerate the JSON object containing the 'raw_log' and the 'rca_schema'."

    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0.1, # for the outputs to be deterministic
        "max_tokens": 4096
    }
    
    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=30)
        resp.raise_for_status() 
        
        content = resp.json()["choices"][0]["message"]["content"]
        extracted_data = json.loads(content)
        
        # Normalize the keys to ensure that they present in the required format
        normalized_data = normalize_keys(extracted_data)
        
        if "raw_log" not in normalized_data or "rca_schema" not in normalized_data:
             logger.error(f"Missing required keys in LLM output: {normalized_data.keys()}")
             return None
             
        return normalized_data
        
    except Exception as e:
        logger.exception(f"LLM Transformation Failed: {e}")
        return None