import os
import requests
import json
import time
from dotenv import load_dotenv
import google.generativeai as genai
from google.generativeai.types import GenerationConfig

load_dotenv()

# Ensure API Key is present
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY is missing. Add it to your .env file.")

# Configure the SDK
genai.configure(api_key=GEMINI_API_KEY)

def normalize_keys(data: dict) -> dict:
    """
    Defensive engineering: Never trust LLM output schema casing.
    Converts all keys to lowercase and strips whitespace.
    """
    if not isinstance(data, dict):
        return {}
    return {str(k).lower().strip(): v for k, v in data.items()}

def generate_synthetic_telemetry(body: str) -> dict:
    # ONE-SHOT PROMPTING: Force the exact schema and style.
    system_prompt = """You are an elite AI Data Engineer constructing a Supervised Fine-Tuning (SFT) dataset for an SRE Root Cause Analysis model.

You will receive two pieces of context:
1. THE SYMPTOM: A GitHub Issue containing user reports and crash logs.
2. THE CURE: A merged Pull Request explaining the fix.

Your objective is to reverse-engineer these into two distinct outputs:

1. 'raw_log': You must format THE SYMPTOM into a highly realistic, unstructured string. It MUST follow this exact structure:
"user_report: [1-2 sentences summarizing the user's problem from the issue]\\n\\nTRACEBACK:\\n[The exact raw stack trace or log from the issue]"
CRITICAL ML CONSTRAINT: The 'raw_log' represents the state of the system BEFORE the fix. You are STRICTLY FORBIDDEN from including any information, code, or context from THE CURE (the PR) inside the 'raw_log'. It must only contain the broken state.

2. 'rca_schema': A strict JSON object representing the Root Cause Analysis derived by analyzing both THE SYMPTOM and THE CURE. 
Keys must be EXACTLY: severity, failing_service, error_code, root_cause_analysis, recommended_remediation.

IMPORTANT:
Do not invent context. If the provided text lacks a clear stack trace/error log, or if the PR does not explain the root cause, you must set the 'root_cause_analysis' value to exactly "INSUFFICIENT_DATA".

=== EXAMPLE INPUT ===
PULL REQUEST AND RELATED ISSUES:
PR: Fix PydanticOutputParser markdown stripping. Resolves #4102.
#4102:
When I chain a prompt with `PydanticOutputParser`, it randomly crashes if the LLM outputs a markdown code block instead of raw JSON.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 256, in __call__
    return self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 26, in parse
    raise OutputParserException(f"Failed to parse Pydantic object: {e}")
langchain.schema.output_parser.OutputParserException: Failed to parse Pydantic object: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

=== EXAMPLE OUTPUT ===
{
  "raw_log": "user_report: When I chain a prompt with `PydanticOutputParser`, it randomly crashes if the LLM outputs a markdown code block instead of raw JSON.\\n\\nTRACEBACK:\\nTraceback (most recent call last):\\n  File \\"/usr/local/lib/python3.10/site-packages/langchain/chains/base.py\\", line 256, in __call__\\n    return self._call(inputs, run_manager=run_manager)\\n  File \\"/usr/local/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py\\", line 26, in parse\\n    raise OutputParserException(f\\"Failed to parse Pydantic object: {e}\\")\\nlangchain.schema.output_parser.OutputParserException: Failed to parse Pydantic object: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)",
  "rca_schema": {
    "severity": "HIGH",
    "failing_service": "langchain.output_parsers.pydantic",
    "error_code": "OutputParserException",
    "root_cause_analysis": "The PydanticOutputParser directly delegates to json.loads() without stripping markdown formatting blocks (e.g., ```json ... ```) that are frequently generated by conversational LLMs. This causes a JSONDecodeError when the parser encounters the markdown backticks.",
    "recommended_remediation": "Update the parser's base logic to include a regex step that strips markdown code block wrappers before attempting to deserialize the JSON string into a Pydantic object."
  }
}

"""
    user_prompt = f"PULL REQUEST AND RELATED ISSUES:\n{body}\n\nGenerate the JSON object containing the 'raw_log' and the 'rca_schema'."

    # Initialize the model with the system prompt natively
    model = genai.GenerativeModel(
        model_name="gemini-2.5-flash",
        system_instruction=system_prompt
    )

    # Force strict JSON output
    generation_config = GenerationConfig(
        temperature=0.1,
        response_mime_type="application/json",
    )
    
    max_retries = 4
    for attempt in range(max_retries):
        try:
            response = model.generate_content(
                user_prompt,
                generation_config=generation_config
            )
            
            content = response.text
            extracted_data = json.loads(content)
            normalized_data = normalize_keys(extracted_data)
            
            if "raw_log" not in normalized_data or "rca_schema" not in normalized_data:
                 print(f"Missing required keys in LLM output: {normalized_data.keys()}")
                 return None
                 
            return normalized_data
            
        except json.JSONDecodeError:
            print("Failed to decode JSON from Gemini. Skipping.")
            return None
        except Exception as e:
            error_msg = str(e)
            print(f"LLM API Exception on attempt {attempt+1}: {error_msg}")
            
            # Handle Google's specific Rate Limit / Quota exceptions (429 / ResourceExhausted)
            if "429" in error_msg or "ResourceExhausted" in error_msg or "quota" in error_msg.lower():
                sleep_time = 15 * (attempt + 1)
                print(f"Gemini Rate Limit Hit. Sleeping for {sleep_time} seconds...")
                time.sleep(sleep_time)
                continue
            
            time.sleep(5)
            
    return None